const mainData = [
  {
    id: '#',
    title: '왕초보 사장님들의\n 단골 만들기 비법',
    tags: ['#소상공인지원', '#카카오상생활동', '#카카오톡채널'],
    date: '',
    category: 'ESG',
    imgSrc: `${import.meta.env.BASE_URL}main/img1.webp`,
    iconSrc: `${import.meta.env.BASE_URL}main/sImg1.webp`,
    content: '마케팅이 어려웠떤 사장님이\n매출 500% 올린 비결',
  },
  {
    id: '#',
    title: '도로 위 히어로즈',
    tags: ['#카카오모빌리티', '#카카오상생활동'],
    date: '',
    category: 'ESG',
    imgSrc: `${import.meta.env.BASE_URL}main/img2.webp`,
    iconSrc: `${import.meta.env.BASE_URL}main/sImg2.webp`,
    content: '...',
  },
  {
    id: '#',
    title: '카카오가 꿈꾸는\n 지속가능한 미래',
    tags: ['#ESG', '#ESG보고서', '#약속과책임', '#카카오'],
    date: '',
    category: 'ESG',
    imgSrc: `${import.meta.env.BASE_URL}main/img3.webp`,
    iconSrc: `${import.meta.env.BASE_URL}main/sImg1.webp`,
    content: '...',
  },
  {
    id: '#',
    title: '진화에 누구보다\n 진심인 편',
    tags: ['#조승연의탐구생활', '#카카오톡', '#카톡이지'],
    date: '',
    category: '서비스',
    imgSrc: `${import.meta.env.BASE_URL}main/img4.webp`,
    iconSrc: `${import.meta.env.BASE_URL}main/sImg1.webp`,
    content: '...',
  },
  {
    id: '#',
    title: '지역 정보 매체에서\n위치 기반 상호작용 플랫폼으로',
    tags: ['#지도플랫폼', '#카카오맵', '#트렌드랭킹'],
    date: '',
    category: '뚝딱뚝딱 성장기',
    imgSrc: `${import.meta.env.BASE_URL}main/img5.webp`,
    iconSrc: `${import.meta.env.BASE_URL}main/sImg3.webp`,
    content: '카카오맵에서 일어난\n24년 간의 업데이트 이야기',
  },
  {
    id: '#',
    title: '100명에게\n물어봤습니다',
    tags: ['#로드트립', '#카카오톡', '#카톡이지'],
    date: '',
    category: '서비스',
    imgSrc: `${import.meta.env.BASE_URL}main/img6.webp`,
    iconSrc: `${import.meta.env.BASE_URL}main/sImg1.webp`,
    content: '...',
  },
  {
    id: '#',
    title: '접근성\n어디까지 고민해 봤나요?',
    tags: ['#디지털접근성', '#카카오톡', '#카톡이지'],
    date: '',
    category: '서비스',
    imgSrc: `${import.meta.env.BASE_URL}main/img7.webp`,
    iconSrc: `${import.meta.env.BASE_URL}main/sImg1.webp`,
    content: '...',
  },
];

export default mainData;
